# reference
genome:
  fasta: /share/references/hg38/fasta/hg38.fa
  star_index: /share/references/hg38/star_gencode_v38_index
  gtf: /share/references/hg38/gencode/gencode.v38.annotation.gtf

# output plots formats
plot_formats:
  - pdf
  - png

# workspace for all jobs to run the pipeline
# all of your output will be place in this dir
workspace: /path/to/workspace

# samples info
samples:
  sample1_rep1:
    fastq:
      lib1:
        fq1: /path/to/sample1_rep1/lib1/read_1.fastq.gz
        fq2: /path/to/sample1_rep1/lib1/read_2.fastq.gz
    meta:
      cell: sample1
      rep: rep1
      group: group1
  sample1_rep2:
    fastq:
      lib1:
        fq1: /path/to/sample1_rep2/lib1/read_1.fastq.gz
        fq2: /path/to/sample1_rep2/lib1/read_2.fastq.gz
    meta:
      cell: sample1
      rep: rep2
      group: group1
  sample2_rep1:
    fastq:
      lib1:
        fq1: /path/to/sample2_rep1/lib1/read_1.fastq.gz
        fq2: /path/to/sample2_rep1/lib1/read_2.fastq.gz
    meta:
      cell: sample2
      rep: rep1
      group: group2
  sample2_rep2:
    fastq:
      lib1:
        fq1: /path/to/sample2_rep2/lib1/read_1.fastq.gz
        fq2: /path/to/sample2_rep2/lib1/read_2.fastq.gz
    meta:
      cell: sample2
      rep: rep2
      group: group1

# comparisons
comparisons:
  group1_vs_group2:
    condition: group
    numerator: group1
    denominator: group2