name: dxpipe
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconductor-deseq2=1.32.0
  - bioconductor-genomicfeatures=1.44.0
  - fastp=0.20.1
  - gtfparse=1.2.1
  - htseq=0.13.5
  - openjdk=11.0.9.1
  - qnorm=0.7.0
  - r-languageserver=0.3.10
  - radian=0.5.10
  - snakemake=6.4.1
  - star=2.7.9a
